// ==========================================================
// BASE DE DADOS 2 - NÃO WM - VERDE
// Gerado para o APP CONTROLE DE COMBUSTÍVEL - CONTROLADORIA
// Total de registros: 74
// ==========================================================

window.BASE_DADOS_2_NAO_WM = [
  {
    "placa": "AZF2E43",
    "identificador": "AZF2E43",
    "numero_serie": "",
    "modelo": "RENAULT FLUENCE PRIVILEGE 2.0 AT",
    "veiculo": "RENAULT FLUENCE PRIVILEGE 2.0 AT",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2014/2015",
    "ano_modelo": "2014/2015",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "BHN4208",
    "identificador": "BHN4208",
    "numero_serie": "",
    "modelo": "TOYOTA/BAND MAX 4.0",
    "veiculo": "TOYOTA/BAND MAX 4.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1992/1992",
    "ano_modelo": "1992/1992",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "BOMBONA",
    "identificador": "BOMBONA",
    "numero_serie": "",
    "modelo": "BOMBONA",
    "veiculo": "BOMBONA",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "-",
    "ano_modelo": "-",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "CAR8E87",
    "identificador": "CAR8E87",
    "numero_serie": "",
    "modelo": "VW/SANTANA CL 1800 I",
    "veiculo": "VW/SANTANA CL 1800 I",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1995/1995",
    "ano_modelo": "1995/1995",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "EBT2G08",
    "identificador": "EBT2G08",
    "numero_serie": "",
    "modelo": "CHEVROLET/ASTRA HB 4P ADVANTAGE 2.0",
    "veiculo": "CHEVROLET/ASTRA HB 4P ADVANTAGE 2.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2008",
    "ano_modelo": "2008/2008",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "GDN5F10",
    "identificador": "GDN5F10",
    "numero_serie": "",
    "modelo": "FOX RUN 1.6 MBV",
    "veiculo": "FOX RUN 1.6 MBV",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2017/2017",
    "ano_modelo": "2017/2017",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "GERADOR",
    "identificador": "GERADOR",
    "numero_serie": "",
    "modelo": "GERADOR",
    "veiculo": "GERADOR",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "-",
    "ano_modelo": "-",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "GYW5182",
    "identificador": "GYW5182",
    "numero_serie": "",
    "modelo": "FIAT/UNO MILLE FIRE FLEX 1.0",
    "veiculo": "FIAT/UNO MILLE FIRE FLEX 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2006/2006",
    "ano_modelo": "2006/2006",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "HKH6A68",
    "identificador": "HKH6A68",
    "numero_serie": "",
    "modelo": "VW/26.220 EURO3 WORKER - PRANCHA",
    "veiculo": "VW/26.220 EURO3 WORKER - PRANCHA",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2010/2010",
    "ano_modelo": "2010/2010",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "JFD6F46",
    "identificador": "JFD6F46",
    "numero_serie": "",
    "modelo": "TOYOTA/BAND MAX 4.0",
    "veiculo": "TOYOTA/BAND MAX 4.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1991/1992",
    "ano_modelo": "1991/1992",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "JTG5F84",
    "identificador": "JTG5F84",
    "numero_serie": "",
    "modelo": "TOYOTA/BAND MAX 3.7",
    "veiculo": "TOYOTA/BAND MAX 3.7",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1995/1995",
    "ano_modelo": "1995/1995",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KGA9H21",
    "identificador": "KGA9H21",
    "numero_serie": "",
    "modelo": "TOYOTA/TOYOTA/BAND MAX 3.8",
    "veiculo": "TOYOTA/TOYOTA/BAND MAX 3.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1989/1989",
    "ano_modelo": "1989/1989",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KGK5112",
    "identificador": "KGK5112",
    "numero_serie": "",
    "modelo": "M.BENZ/710",
    "veiculo": "M.BENZ/710",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2005/2005",
    "ano_modelo": "2005/2005",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KHR1E71",
    "identificador": "KHR1E71",
    "numero_serie": "",
    "modelo": "POLO SEDAN 1.6",
    "veiculo": "POLO SEDAN 1.6",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2008",
    "ano_modelo": "2008/2008",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KIQ7C35",
    "identificador": "KIQ7C35",
    "numero_serie": "",
    "modelo": "TOYOTA/BAND MAX 4.0",
    "veiculo": "TOYOTA/BAND MAX 4.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1992/1992",
    "ano_modelo": "1992/1992",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KLZ0F54",
    "identificador": "KLZ0F54",
    "numero_serie": "",
    "modelo": "VW/13.150",
    "veiculo": "VW/13.150",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2003/2003",
    "ano_modelo": "2003/2003",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KMD1293",
    "identificador": "KMD1293",
    "numero_serie": "",
    "modelo": "HONDA/FIT LX 1.4 (WILLIAM)",
    "veiculo": "HONDA/FIT LX 1.4 (WILLIAM)",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2008",
    "ano_modelo": "2008/2008",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KNO3610",
    "identificador": "KNO3610",
    "numero_serie": "",
    "modelo": "MERCEDEZ BENZ/MPOLO VIALE U",
    "veiculo": "MERCEDEZ BENZ/MPOLO VIALE U",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2008",
    "ano_modelo": "2008/2008",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "KNO3G10",
    "identificador": "KNO3G10",
    "numero_serie": "",
    "modelo": "MERCEDEZ BENZ / MPOLO VIALE U",
    "veiculo": "MERCEDEZ BENZ / MPOLO VIALE U",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2008",
    "ano_modelo": "2008/2008",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "LLE4887",
    "identificador": "LLE4887",
    "numero_serie": "",
    "modelo": "VW/24.220 EURO3 WORKER",
    "veiculo": "VW/24.220 EURO3 WORKER",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2009/2009",
    "ano_modelo": "2009/2009",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "LLE4B87",
    "identificador": "LLE4B87",
    "numero_serie": "",
    "modelo": "MERCEDEZ BENZ/OF1418 NEOBUS MEGA",
    "veiculo": "MERCEDEZ BENZ/OF1418 NEOBUS MEGA",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2010/2010",
    "ano_modelo": "2010/2010",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "LLW5F36",
    "identificador": "LLW5F36",
    "numero_serie": "",
    "modelo": "MERCEDEZ BENZ / ATRON 1319",
    "veiculo": "MERCEDEZ BENZ / ATRON 1319",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2013/2013",
    "ano_modelo": "2013/2013",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "MOTOSSERRA",
    "identificador": "MOTOSSERRA",
    "numero_serie": "",
    "modelo": "MOTOSSERRA",
    "veiculo": "MOTOSSERRA",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "-",
    "ano_modelo": "-",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "NNL5J30",
    "identificador": "NNL5J30",
    "numero_serie": "",
    "modelo": "GM/CELTA 4P LIFE 1.0",
    "veiculo": "GM/CELTA 4P LIFE 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2008/2009",
    "ano_modelo": "2008/2009",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "NYD1I57",
    "identificador": "NYD1I57",
    "numero_serie": "",
    "modelo": "M.BENZ/ATRON 1319",
    "veiculo": "M.BENZ/ATRON 1319",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2012/2012",
    "ano_modelo": "2012/2012",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "OBV3J68",
    "identificador": "OBV3J68",
    "numero_serie": "",
    "modelo": "TOYOTA/BAND MAX 3.8",
    "veiculo": "TOYOTA/BAND MAX 3.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "1989/1989",
    "ano_modelo": "1989/1989",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "OXD1F36",
    "identificador": "OXD1F36",
    "numero_serie": "",
    "modelo": "VW/24.280 CRM 6X2 - CM LOCAÇÕES",
    "veiculo": "VW/24.280 CRM 6X2 - CM LOCAÇÕES",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2013/2014",
    "ano_modelo": "2013/2014",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "PCC7I72",
    "identificador": "PCC7I72",
    "numero_serie": "",
    "modelo": "HYUNDAI/HB20 1.0M COMFOR - LIDYANE",
    "veiculo": "HYUNDAI/HB20 1.0M COMFOR - LIDYANE",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2014/2025",
    "ano_modelo": "2014/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "PDK8610",
    "identificador": "PDK8610",
    "numero_serie": "",
    "modelo": "STRADA FREEDOM CD 1.4",
    "veiculo": "STRADA FREEDOM CD 1.4",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2018/2019",
    "ano_modelo": "2018/2019",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "PDK8G10",
    "identificador": "PDK8G10",
    "numero_serie": "",
    "modelo": "STRADA FREEDOM CD 1.4",
    "veiculo": "STRADA FREEDOM CD 1.4",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2018/2019",
    "ano_modelo": "2018/2019",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "PJK2F57",
    "identificador": "PJK2F57",
    "numero_serie": "",
    "modelo": "CHEVROLET ONIX MT LT 1.0",
    "veiculo": "CHEVROLET ONIX MT LT 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QGG5B69",
    "identificador": "QGG5B69",
    "numero_serie": "",
    "modelo": "VW/24.280 CRM 6X2",
    "veiculo": "VW/24.280 CRM 6X2",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QGP0F84",
    "identificador": "QGP0F84",
    "numero_serie": "",
    "modelo": "CHEV/SPIN 1.8L MT LTZ",
    "veiculo": "CHEV/SPIN 1.8L MT LTZ",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2018/2018",
    "ano_modelo": "2018/2018",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QGT2F03",
    "identificador": "QGT2F03",
    "numero_serie": "",
    "modelo": "HONDA/CIVIC LXR",
    "veiculo": "HONDA/CIVIC LXR",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2016/2016",
    "ano_modelo": "2016/2016",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QGZ1A78",
    "identificador": "QGZ1A78",
    "numero_serie": "",
    "modelo": "TOYOTA/COROLLA GLI 20",
    "veiculo": "TOYOTA/COROLLA GLI 20",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QJW9B48",
    "identificador": "QJW9B48",
    "numero_serie": "",
    "modelo": "CHEV/CRUZE LT NB AT 1.4 TURBO",
    "veiculo": "CHEV/CRUZE LT NB AT 1.4 TURBO",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2019/2019",
    "ano_modelo": "2019/2019",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "QMD0629",
    "identificador": "QMD0629",
    "numero_serie": "",
    "modelo": "VW/24.280 CRM 6X2",
    "veiculo": "VW/24.280 CRM 6X2",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2018/2019",
    "ano_modelo": "2018/2019",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RHB7B51",
    "identificador": "RHB7B51",
    "numero_serie": "",
    "modelo": "I/TOYOTA HILUX CDLOWM4FD 2.8",
    "veiculo": "I/TOYOTA HILUX CDLOWM4FD 2.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2021/2021",
    "ano_modelo": "2021/2021",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RQC0D66",
    "identificador": "RQC0D66",
    "numero_serie": "",
    "modelo": "RENAULT DUSTER ICO CVT 1.6",
    "veiculo": "RENAULT DUSTER ICO CVT 1.6",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2023/2024",
    "ano_modelo": "2023/2024",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RQE2J49",
    "identificador": "RQE2J49",
    "numero_serie": "",
    "modelo": "NISSAN/KICKS EXCLUSI CVT 1.6 - WEVERTON",
    "veiculo": "NISSAN/KICKS EXCLUSI CVT 1.6 - WEVERTON",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2023/2024",
    "ano_modelo": "2023/2024",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RQI1A34",
    "identificador": "RQI1A34",
    "numero_serie": "",
    "modelo": "MITSUBISH/TRITON SPORT HPE S",
    "veiculo": "MITSUBISH/TRITON SPORT HPE S",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RZO0H19",
    "identificador": "RZO0H19",
    "numero_serie": "",
    "modelo": "HONDA/CG 160 FAN",
    "veiculo": "HONDA/CG 160 FAN",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2022/2022",
    "ano_modelo": "2022/2022",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SAPINHO",
    "identificador": "SAPINHO",
    "numero_serie": "",
    "modelo": "SAPINHO",
    "veiculo": "SAPINHO",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "-",
    "ano_modelo": "-",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SDO9G87",
    "identificador": "SDO9G87",
    "numero_serie": "",
    "modelo": "I/TOYOTA HILUX CDLOWM4FD 2.8",
    "veiculo": "I/TOYOTA HILUX CDLOWM4FD 2.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2024",
    "ano_modelo": "2024/2024",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SKA0I49",
    "identificador": "SKA0I49",
    "numero_serie": "",
    "modelo": "TOYOTA HILUX CDSR A4FD 2.8",
    "veiculo": "TOYOTA HILUX CDSR A4FD 2.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2024",
    "ano_modelo": "2024/2024",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SKA3627",
    "identificador": "SKA3627",
    "numero_serie": "",
    "modelo": "HB20 M COMFORT 1.0",
    "veiculo": "HB20 M COMFORT 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SKA3G27",
    "identificador": "SKA3G27",
    "numero_serie": "",
    "modelo": "HB20 COMFORT 1.0",
    "veiculo": "HB20 COMFORT 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "SVO6880",
    "identificador": "SVO6880",
    "numero_serie": "",
    "modelo": "VW/POLO TRACK MA 1.0",
    "veiculo": "VW/POLO TRACK MA 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2023/2024",
    "ano_modelo": "2023/2024",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TCN6I09",
    "identificador": "TCN6I09",
    "numero_serie": "",
    "modelo": "STRADA FREEDOM CD13",
    "veiculo": "STRADA FREEDOM CD13",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TCT0F20",
    "identificador": "TCT0F20",
    "numero_serie": "",
    "modelo": "FIAT/ARGO DRIVE 1.0",
    "veiculo": "FIAT/ARGO DRIVE 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "20242025",
    "ano_modelo": "20242025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TCV1B15",
    "identificador": "TCV1B15",
    "numero_serie": "",
    "modelo": "FIAT/TORO FREED T270 AT6 1.3",
    "veiculo": "FIAT/TORO FREED T270 AT6 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TCV9E29",
    "identificador": "TCV9E29",
    "numero_serie": "",
    "modelo": "FIAT/STRADA FREEDOM CD 1.3",
    "veiculo": "FIAT/STRADA FREEDOM CD 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TCX0D51",
    "identificador": "TCX0D51",
    "numero_serie": "",
    "modelo": "POLO TRACK MA",
    "veiculo": "POLO TRACK MA",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TDK3D80",
    "identificador": "TDK3D80",
    "numero_serie": "",
    "modelo": "VW/POLO TRACK MA 1.0",
    "veiculo": "VW/POLO TRACK MA 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TDK9D80",
    "identificador": "TDK9D80",
    "numero_serie": "",
    "modelo": "FIAT/STRADA FREEDOM CD 1.3",
    "veiculo": "FIAT/STRADA FREEDOM CD 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TEB3F95",
    "identificador": "TEB3F95",
    "numero_serie": "",
    "modelo": "FIAT/TORO VOLC AT9 4X4 2.2",
    "veiculo": "FIAT/TORO VOLC AT9 4X4 2.2",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2025",
    "ano_modelo": "2025/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TEN9G16",
    "identificador": "TEN9G16",
    "numero_serie": "",
    "modelo": "FIAT/STRADA FREEDOM CD 1.3",
    "veiculo": "FIAT/STRADA FREEDOM CD 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2025",
    "ano_modelo": "2025/2025",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TEO9J40",
    "identificador": "TEO9J40",
    "numero_serie": "",
    "modelo": "VW/SAVEIRO CS RB MF 1.6",
    "veiculo": "VW/SAVEIRO CS RB MF 1.6",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TER3G62",
    "identificador": "TER3G62",
    "numero_serie": "",
    "modelo": "FIAT/STRADA FREEDOM CD 1.3",
    "veiculo": "FIAT/STRADA FREEDOM CD 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TSP8F60",
    "identificador": "TSP8F60",
    "numero_serie": "",
    "modelo": "JEEP/RENEGADE ALTIT T270 1.3",
    "veiculo": "JEEP/RENEGADE ALTIT T270 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TXB2B98",
    "identificador": "TXB2B98",
    "numero_serie": "",
    "modelo": "RENAULT KWID ZEN 1.0",
    "veiculo": "RENAULT KWID ZEN 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TXM6I73",
    "identificador": "TXM6I73",
    "numero_serie": "",
    "modelo": "HYUNDAI/HB20 10M COMFORT",
    "veiculo": "HYUNDAI/HB20 10M COMFORT",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TXU6G47",
    "identificador": "TXU6G47",
    "numero_serie": "",
    "modelo": "POLO TRACK MA 1.0",
    "veiculo": "POLO TRACK MA 1.0",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TXV3C85",
    "identificador": "TXV3C85",
    "numero_serie": "",
    "modelo": "STRADA FREEDOM CD 1.3",
    "veiculo": "STRADA FREEDOM CD 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TYE4F47",
    "identificador": "TYE4F47",
    "numero_serie": "",
    "modelo": "VW/SAVEIRO CS RB MF 1.6",
    "veiculo": "VW/SAVEIRO CS RB MF 1.6",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TYN3G28",
    "identificador": "TYN3G28",
    "numero_serie": "",
    "modelo": "FIAT/TORO FREED T270 AT 1.3",
    "veiculo": "FIAT/TORO FREED T270 AT 1.3",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2026/2026",
    "ano_modelo": "2026/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "TZA0D49",
    "identificador": "TZA0D49",
    "numero_serie": "",
    "modelo": "CHEVROLET S10 LTZ DD4A 2.8",
    "veiculo": "CHEVROLET S10 LTZ DD4A 2.8",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2025/2026",
    "ano_modelo": "2025/2026",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "OQA3606",
    "identificador": "OQA3606",
    "numero_serie": "",
    "modelo": "VW/26.280 CRM 6X4",
    "veiculo": "VW/26.280 CRM 6X4",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2012/2012",
    "ano_modelo": "2012/2012",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RTR2C98",
    "identificador": "RTR2C98",
    "numero_serie": "",
    "modelo": "VW/13.190 CRM 4X2 - CAM PERFURATRIZ  EMPRESA APL",
    "veiculo": "VW/13.190 CRM 4X2 - CAM PERFURATRIZ  EMPRESA APL",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "OGG7J98",
    "identificador": "OGG7J98",
    "numero_serie": "",
    "modelo": "HYUNDAI/HB20 1.0 M",
    "veiculo": "HYUNDAI/HB20 1.0 M",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2013/2014",
    "ano_modelo": "2013/2014",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "FCO2G61",
    "identificador": "FCO2G61",
    "numero_serie": "",
    "modelo": "NISSAN/KICKS SL CVT",
    "veiculo": "NISSAN/KICKS SL CVT",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2017/2018",
    "ano_modelo": "2017/2018",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "MTY9H99",
    "identificador": "MTY9H99",
    "numero_serie": "",
    "modelo": "MERCEDEZ BENZ / MPOLO TORINO U",
    "veiculo": "MERCEDEZ BENZ / MPOLO TORINO U",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2011/2011",
    "ano_modelo": "2011/2011",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RETROSN",
    "identificador": "RETROSN",
    "numero_serie": "RETROSN",
    "modelo": "RETROESCAVADEIRA S/Nº",
    "veiculo": "RETROESCAVADEIRA S/Nº",
    "equipamento": "RETROESCAVADEIRA S/Nº",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "",
    "consumo": "",
    "ano": "",
    "ano_modelo": "",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  },
  {
    "placa": "RETROCAT41645",
    "identificador": "RETROCAT41645",
    "numero_serie": "RETROCAT41645",
    "modelo": "RETRO CAT 416 (45)",
    "veiculo": "RETRO CAT 416 (45)",
    "equipamento": "RETRO CAT 416 (45)",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "",
    "consumo": "",
    "ano": "",
    "ano_modelo": "",
    "frota": "",
    "status": "TERCEIRO / NÃO WM",
    "local": "",
    "empresa": "NÃO WM",
    "condutor": "",
    "origem": "BASE DE DADOS 2",
    "pertence_wm": "NÃO",
    "cor_relatorio": "VERDE"
  }
];
