// ==========================================================
// BASE DE DADOS WM - AZUL
// Gerado para o APP CONTROLE DE COMBUSTÍVEL - CONTROLADORIA
// Total de registros: 44
// ==========================================================

window.BASE_DADOS_WM = [
  {
    "placa": "NNR9133",
    "identificador": "NNR9133",
    "numero_serie": "",
    "modelo": "M. BENZ 2726 6X4 - IMAP 55",
    "veiculo": "M. BENZ 2726 6X4 - IMAP 55",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2011/2011",
    "ano_modelo": "2011/2011",
    "frota": "01",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NOD6528",
    "identificador": "NOD6528",
    "numero_serie": "",
    "modelo": "M. BENZ 2726 6X4 - ARGOS 43",
    "veiculo": "M. BENZ 2726 6X4 - ARGOS 43",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "0",
    "consumo": "0",
    "ano": "2011/2011",
    "ano_modelo": "2011/2011",
    "frota": "02",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NOB0F35",
    "identificador": "NOB0F35",
    "numero_serie": "",
    "modelo": "M. BENZ 2726 6X4 - ARGOS 43",
    "veiculo": "M. BENZ 2726 6X4 - ARGOS 43",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2011/2011",
    "ano_modelo": "2011/2011",
    "frota": "03",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWE0I79",
    "identificador": "OWE0I79",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 4X2 R - CAB SUPLEMENTAR 23 LUGARES",
    "veiculo": "VOLVO VM 220 4X2 R - CAB SUPLEMENTAR 23 LUGARES",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "CABINADO",
    "consumo": "CABINADO",
    "ano": "2013/2013",
    "ano_modelo": "2013/2013",
    "frota": "04",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJT7952",
    "identificador": "OJT7952",
    "numero_serie": "",
    "modelo": "SANY STC800 - GUINDASTE 80 TON",
    "veiculo": "SANY STC800 - GUINDASTE 80 TON",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "GUINDASTE",
    "consumo": "GUINDASTE",
    "ano": "2013/2013",
    "ano_modelo": "2013/2013",
    "frota": "05",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWC7842",
    "identificador": "OWC7842",
    "numero_serie": "",
    "modelo": "SANY STC300B - GUINDASTE 30 TON",
    "veiculo": "SANY STC300B - GUINDASTE 30 TON",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "GUINDASTE",
    "consumo": "GUINDASTE",
    "ano": "2013/2013",
    "ano_modelo": "2013/2013",
    "frota": "06",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWB3382",
    "identificador": "OWB3382",
    "numero_serie": "",
    "modelo": "VOLVO VM 270 6X2 - PALFINGER 45",
    "veiculo": "VOLVO VM 270 6X2 - PALFINGER 45",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2014/2014",
    "ano_modelo": "2014/2014",
    "frota": "07",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJZ8873",
    "identificador": "OJZ8873",
    "numero_serie": "",
    "modelo": "IVECO TECTOR 240E22 - TKA 45",
    "veiculo": "IVECO TECTOR 240E22 - TKA 45",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2014/2014",
    "ano_modelo": "2014/2014",
    "frota": "08",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWB7423",
    "identificador": "OWB7423",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 4X2 R - LUNA 20",
    "veiculo": "VOLVO VM 220 4X2 R - LUNA 20",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2014/2014",
    "ano_modelo": "2014/2014",
    "frota": "09",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGB9419",
    "identificador": "QGB9419",
    "numero_serie": "",
    "modelo": "SANY STC300B - GUINDASTE 30 TON",
    "veiculo": "SANY STC300B - GUINDASTE 30 TON",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "GUINDASTE",
    "consumo": "GUINDASTE",
    "ano": "2014/2014",
    "ano_modelo": "2014/2014",
    "frota": "10",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWG8D41",
    "identificador": "OWG8D41",
    "numero_serie": "",
    "modelo": "FORD CARGO 2623 6X4 - CAÇAMBA 12/14M³",
    "veiculo": "FORD CARGO 2623 6X4 - CAÇAMBA 12/14M³",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "BASCULANTE",
    "consumo": "BASCULANTE",
    "ano": "2014/2015",
    "ano_modelo": "2014/2015",
    "frota": "11",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGD8933",
    "identificador": "QGD8933",
    "numero_serie": "",
    "modelo": "VOLVO VM 270 6X4 - TKA 52",
    "veiculo": "VOLVO VM 270 6X4 - TKA 52",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "12",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGE3A73",
    "identificador": "QGE3A73",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 4X2 - TKA 21",
    "veiculo": "VOLVO VM 220 4X2 - TKA 21",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "CABINADO",
    "consumo": "CABINADO",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "13",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGE5E33",
    "identificador": "QGE5E33",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 4X2 - TKA 21",
    "veiculo": "VOLVO VM 220 4X2 - TKA 21",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "CABINADO",
    "consumo": "CABINADO",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "14",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGE3C53",
    "identificador": "QGE3C53",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 6X2 - TKA 45",
    "veiculo": "VOLVO VM 220 6X2 - TKA 45",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "15",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGE3E53",
    "identificador": "QGE3E53",
    "numero_serie": "",
    "modelo": "VOLVO VM 220 6X2 - BAÚ",
    "veiculo": "VOLVO VM 220 6X2 - BAÚ",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "BAÚ",
    "consumo": "BAÚ",
    "ano": "2015/2015",
    "ano_modelo": "2015/2015",
    "frota": "16",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OWD4501",
    "identificador": "OWD4501",
    "numero_serie": "",
    "modelo": "CHEVROLET MONTANA 1.4 LS",
    "veiculo": "CHEVROLET MONTANA 1.4 LS",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2014/2015",
    "ano_modelo": "2014/2015",
    "frota": "17",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OYR0118",
    "identificador": "OYR0118",
    "numero_serie": "",
    "modelo": "FIAT FIORINO 1.4 - AMBULÂNCIA TIPO B",
    "veiculo": "FIAT FIORINO 1.4 - AMBULÂNCIA TIPO B",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "AMBULÂNCIA",
    "consumo": "AMBULÂNCIA",
    "ano": "2014/2014",
    "ano_modelo": "2014/2014",
    "frota": "18",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OBG4440",
    "identificador": "OBG4440",
    "numero_serie": "",
    "modelo": "CINTROEN JUMPER",
    "veiculo": "CINTROEN JUMPER",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "VAN",
    "consumo": "VAN",
    "ano": "2013/2013",
    "ano_modelo": "2013/2013",
    "frota": "19",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGM2168",
    "identificador": "QGM2168",
    "numero_serie": "",
    "modelo": "RENAULT SANDERO",
    "veiculo": "RENAULT SANDERO",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "LEVE",
    "consumo": "LEVE",
    "ano": "2017/2018",
    "ano_modelo": "2017/2018",
    "frota": "20",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGP3J70",
    "identificador": "QGP3J70",
    "numero_serie": "",
    "modelo": "VW SAVEIRO ROBUST 1.6 CS",
    "veiculo": "VW SAVEIRO ROBUST 1.6 CS",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2016/2017",
    "ano_modelo": "2016/2017",
    "frota": "21",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGQ8H57",
    "identificador": "QGQ8H57",
    "numero_serie": "",
    "modelo": "FIAT MOBI LIKE",
    "veiculo": "FIAT MOBI LIKE",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "LEVE",
    "consumo": "LEVE",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "22",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGW9B48",
    "identificador": "QGW9B48",
    "numero_serie": "",
    "modelo": "FIAT UNO VIVACE",
    "veiculo": "FIAT UNO VIVACE",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "LEVE",
    "consumo": "LEVE",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "23",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJY7A83",
    "identificador": "OJY7A83",
    "numero_serie": "",
    "modelo": "RENAULT OROCH INTENSE 1.6 M",
    "veiculo": "RENAULT OROCH INTENSE 1.6 M",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2014/2015",
    "ano_modelo": "2014/2015",
    "frota": "24",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGW8305",
    "identificador": "QGW8305",
    "numero_serie": "",
    "modelo": "CHEVROLET TRAILBLAZER LTZ",
    "veiculo": "CHEVROLET TRAILBLAZER LTZ",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "SUV",
    "consumo": "SUV",
    "ano": "2014/2015",
    "ano_modelo": "2014/2015",
    "frota": "25",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "RQB3C44",
    "identificador": "RQB3C44",
    "numero_serie": "",
    "modelo": "FIAT STRADA FREEDOM 1.3 CD",
    "veiculo": "FIAT STRADA FREEDOM 1.3 CD",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2023/2023",
    "ano_modelo": "2023/2023",
    "frota": "26",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJY9A82",
    "identificador": "OJY9A82",
    "numero_serie": "",
    "modelo": "FIAT STRADA ENDURANCE 1.4 CS",
    "veiculo": "FIAT STRADA ENDURANCE 1.4 CS",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2023/2023",
    "ano_modelo": "2023/2023",
    "frota": "27",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJY9B02",
    "identificador": "OJY9B02",
    "numero_serie": "",
    "modelo": "FIAT STRADA ENDURANCE 1.4 CS",
    "veiculo": "FIAT STRADA ENDURANCE 1.4 CS",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2023/2023",
    "ano_modelo": "2023/2023",
    "frota": "28",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "OJY6H22",
    "identificador": "OJY6H22",
    "numero_serie": "",
    "modelo": "M. BENZ ATEGO 2730 6X4 CE - TKA 45",
    "veiculo": "M. BENZ ATEGO 2730 6X4 CE - TKA 45",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2022/2023",
    "ano_modelo": "2022/2023",
    "frota": "29",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "JKT6D94",
    "identificador": "JKT6D94",
    "numero_serie": "",
    "modelo": "TOYOTA BANDEIRANTE 4X4 - 12 LUGARES",
    "veiculo": "TOYOTA BANDEIRANTE 4X4 - 12 LUGARES",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "UTILITÁRIO",
    "consumo": "UTILITÁRIO",
    "ano": "1993/1993",
    "ano_modelo": "1993/1993",
    "frota": "31",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGQ8C57",
    "identificador": "QGQ8C57",
    "numero_serie": "",
    "modelo": "FIAT MOBI LIKE",
    "veiculo": "FIAT MOBI LIKE",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "LEVE",
    "consumo": "LEVE",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "32",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGK7994",
    "identificador": "QGK7994",
    "numero_serie": "",
    "modelo": "FIAT MOBI LIKE",
    "veiculo": "FIAT MOBI LIKE",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "LEVE",
    "consumo": "LEVE",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "33",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGY2A62",
    "identificador": "QGY2A62",
    "numero_serie": "",
    "modelo": "VW SAVEIRO ROBUST 1.6 CS",
    "veiculo": "VW SAVEIRO ROBUST 1.6 CS",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "34",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "RGE5I54",
    "identificador": "RGE5I54",
    "numero_serie": "",
    "modelo": "VW AMAROK SE 4X4 CD",
    "veiculo": "VW AMAROK SE 4X4 CD",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2019/2020",
    "ano_modelo": "2019/2020",
    "frota": "35",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "RQL5B10",
    "identificador": "RQL5B10",
    "numero_serie": "",
    "modelo": "VW SAVEIRO ROBUST 1.6 CD",
    "veiculo": "VW SAVEIRO ROBUST 1.6 CD",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "36",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "TSP1H98",
    "identificador": "TSP1H98",
    "numero_serie": "",
    "modelo": "VW SAVEIRO ROBUST 1.6 CD",
    "veiculo": "VW SAVEIRO ROBUST 1.6 CD",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "PICK-UP",
    "consumo": "PICK-UP",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "37",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "TSP0F57",
    "identificador": "TSP0F57",
    "numero_serie": "",
    "modelo": "VW 31.320 + ING 60",
    "veiculo": "VW 31.320 + ING 60",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "MUNCK",
    "consumo": "MUNCK",
    "ano": "2024/2025",
    "ano_modelo": "2024/2025",
    "frota": "38",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "QGH4J26",
    "identificador": "QGH4J26",
    "numero_serie": "",
    "modelo": "KIA UK2500 HDV 2.5 TURBO (BONGO MELOSA) 2.000 litros",
    "veiculo": "KIA UK2500 HDV 2.5 TURBO (BONGO MELOSA) 2.000 litros",
    "equipamento": "",
    "tipo_cadastro": "VEÍCULO",
    "tipo": "",
    "consumo": "",
    "ano": "2017/2018",
    "ano_modelo": "2017/2018",
    "frota": "",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NNAH28666",
    "identificador": "NNAH28666",
    "numero_serie": "NNAH28666",
    "modelo": "CASE 580N 4X4 CABINADA (RET 1)",
    "veiculo": "CASE 580N 4X4 CABINADA (RET 1)",
    "equipamento": "CASE 580N 4X4 CABINADA (RET 1)",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "RETROESCAVADEIRA",
    "consumo": "RETROESCAVADEIRA",
    "ano": "2022/2022",
    "ano_modelo": "2022/2022",
    "frota": "01",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NNAH29170",
    "identificador": "NNAH29170",
    "numero_serie": "NNAH29170",
    "modelo": "CASE 580N 4X4 CABINADA (RET 2)",
    "veiculo": "CASE 580N 4X4 CABINADA (RET 2)",
    "equipamento": "CASE 580N 4X4 CABINADA (RET 2)",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "RETROESCAVADEIRA",
    "consumo": "RETROESCAVADEIRA",
    "ano": "2022/2022",
    "ano_modelo": "2022/2022",
    "frota": "02",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NNAH29833",
    "identificador": "NNAH29833",
    "numero_serie": "NNAH29833",
    "modelo": "CASE 580N 4X4 CABINADA (RET 3)",
    "veiculo": "CASE 580N 4X4 CABINADA (RET 3)",
    "equipamento": "CASE 580N 4X4 CABINADA (RET 3)",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "RETROESCAVADEIRA",
    "consumo": "RETROESCAVADEIRA",
    "ano": "2022/2022",
    "ano_modelo": "2022/2022",
    "frota": "03",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "NNAH28680",
    "identificador": "NNAH28680",
    "numero_serie": "NNAH28680",
    "modelo": "CASE 580N 4X4 CABINADA (RET 4)",
    "veiculo": "CASE 580N 4X4 CABINADA (RET 4)",
    "equipamento": "CASE 580N 4X4 CABINADA (RET 4)",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "RETROESCAVADEIRA",
    "consumo": "RETROESCAVADEIRA",
    "ano": "2022/2022",
    "ano_modelo": "2022/2022",
    "frota": "04",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "BF08H01831",
    "identificador": "BF08H01831",
    "numero_serie": "BF08H01831",
    "modelo": "FIORI DB460SL 4M³",
    "veiculo": "FIORI DB460SL 4M³",
    "equipamento": "FIORI DB460SL 4M³",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "AUTO-BETONEIRA",
    "consumo": "AUTO-BETONEIRA",
    "ano": "2023/2023",
    "ano_modelo": "2023/2023",
    "frota": "05",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  },
  {
    "placa": "XUG0215CRPA02019",
    "identificador": "XUG0215CRPA02019",
    "numero_serie": "XUG0215CRPA02019",
    "modelo": "XCMG XE225BR",
    "veiculo": "XCMG XE225BR",
    "equipamento": "XCMG XE225BR",
    "tipo_cadastro": "EQUIPAMENTO",
    "tipo": "ESCAVADEIRA HIDRAULICA",
    "consumo": "ESCAVADEIRA HIDRAULICA",
    "ano": "2024/2024",
    "ano_modelo": "2024/2024",
    "frota": "06",
    "status": "ATIVO",
    "local": "",
    "empresa": "WM",
    "condutor": "",
    "origem": "BASE DE DADOS",
    "pertence_wm": "SIM",
    "cor_relatorio": "AZUL"
  }
];
